# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffyml < Formula
  desc "Structural diff tool for YAML files"
  homepage "https://github.com/szhekpisov/diffyml"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.6.1/diffyml_1.6.1_darwin_amd64.tar.gz"
      sha256 "bf2a0bf9c3c784c5c2a3efc1b4758d7eee46fa03c820f4fa90e707b08355340c"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.6.1/diffyml_1.6.1_darwin_arm64.tar.gz"
      sha256 "564367bf7239d1406554072f5221d16136df90ab66e5a23b1f75158d483742dc"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.6.1/diffyml_1.6.1_linux_amd64.tar.gz"
      sha256 "9356f093c18eebc4ddf9c7cfbe80ea3c6c4e24022e15d7fabfb78dda7cd8419b"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.6.1/diffyml_1.6.1_linux_arm64.tar.gz"
      sha256 "fb6b651a8244935732e75f0731901c9963aed1cffab553ed7b296e237a644c7b"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/diffyml --version")

    (testpath/"file1.yaml").write <<~YAML
      name: test
      value: 1
    YAML

    (testpath/"file2.yaml").write <<~YAML
      name: test
      value: 2
    YAML

    output = shell_output("#{bin}/diffyml #{testpath}/file1.yaml #{testpath}/file2.yaml")
    assert_match "value", output
  end
end
