# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffyml < Formula
  desc "Structural diff tool for YAML files"
  homepage "https://github.com/szhekpisov/diffyml"
  version "1.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.5.5/diffyml_1.5.5_darwin_amd64.tar.gz"
      sha256 "44d29d0c75a38d8e714d837b5b8a77ad397e096167d255cd523cc962601c1e7e"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.5.5/diffyml_1.5.5_darwin_arm64.tar.gz"
      sha256 "8689418057e35d5ea06669c7449255ca0d3ce40287ad9ec5f4fddb747c590ac4"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.5.5/diffyml_1.5.5_linux_amd64.tar.gz"
      sha256 "af3de55c70db6ed67acd76ad285065ec27ded03a1e7846f6ec1967b097c6f13c"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.5.5/diffyml_1.5.5_linux_arm64.tar.gz"
      sha256 "ca78e60a700b7214c502080dea7d5b3ba443082b15a1ad1fb16d0d67e11a7c08"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/diffyml --version")

    (testpath/"file1.yaml").write <<~YAML
      name: test
      value: 1
    YAML

    (testpath/"file2.yaml").write <<~YAML
      name: test
      value: 2
    YAML

    output = shell_output("#{bin}/diffyml #{testpath}/file1.yaml #{testpath}/file2.yaml")
    assert_match "value", output
  end
end
