# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffyml < Formula
  desc "Structural diff tool for YAML files"
  homepage "https://github.com/szhekpisov/diffyml"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.7.0/diffyml_1.7.0_darwin_amd64.tar.gz"
      sha256 "391b46c6798602809401d9829254800dc899ef96ac4ba637cc14409f4e1c527a"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.7.0/diffyml_1.7.0_darwin_arm64.tar.gz"
      sha256 "402cb66d9a837a7dff1abb798a1d2b93538f6eef767ab94e87c01f7526775987"

      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.7.0/diffyml_1.7.0_linux_amd64.tar.gz"
      sha256 "d8bc6913a44b402eaca4a89d4810cb8f96d30550e57829ea5e09f0f3eb8bece2"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szhekpisov/diffyml/releases/download/v1.7.0/diffyml_1.7.0_linux_arm64.tar.gz"
      sha256 "f6ae0b085258a3487bfb0ee78c09bff40d121c99887c1b55a70bb43a0326eeaa"
      define_method(:install) do
        bin.install "diffyml"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/diffyml --version")

    (testpath/"file1.yaml").write <<~YAML
      name: test
      value: 1
    YAML

    (testpath/"file2.yaml").write <<~YAML
      name: test
      value: 2
    YAML

    output = shell_output("#{bin}/diffyml #{testpath}/file1.yaml #{testpath}/file2.yaml")
    assert_match "value", output
  end
end
